# Generated by Django 4.2.5 on 2023-09-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='logout_time',
        ),
    ]
