# Generated by Django 4.2.5 on 2023-09-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_useractivity_logout_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
