# Generated by Django 4.2.5 on 2023-09-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Usersdata',
        ),
    ]
